project_id = "iaksojdlmenbvfsigayc"

[functions.reset-user-password]
verify_jwt = false

[functions.create-member]
verify_jwt = false

[functions.update-member-profile]
verify_jwt = false

[functions.google-calendar-oauth-callback]
verify_jwt = false

[functions.public-project-view]
verify_jwt = false
